config/routes.rb
Rails.application.routes.draw do
  resources :factorialls
  root "factorialls#index"

end

app/models/factoriall.rb
class Factoriall < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/factorialls_controller.rb
class FactoriallsController < ApplicationController
  before_action :set_factoriall, only: [:show, :edit, :update, :destroy]

  # GET /factorialls
  # GET /factorialls.json
  def index
    @factorialls = Factoriall.all
    if @factorialls.empty?
      Thread.new do
        res = BigDecimal.new(0)
        5.times do |n|
          st = n == 0 ? 1 : 26**n + 1
          en = 26**(n+1)
          res = (st..en).inject(res){|sum, k| sum + Math.log2(k)}
          Factoriall.create n: (n+1), result: res.to_s
        end
      end
    end
  end

  # GET /factorialls/1
  # GET /factorialls/1.json
  def show
  end

  # GET /factorialls/new
  def new
    @factoriall = Factoriall.new
  end

  # GET /factorialls/1/edit
  def edit
  end

  # POST /factorialls
  # POST /factorialls.json
  def create
    @factoriall = Factoriall.new(factoriall_params)

    respond_to do |format|
      if @factoriall.save
        format.html { redirect_to @factoriall, notice: 'Factoriall was successfully created.' }
        format.json { render :show, status: :created, location: @factoriall }
      else
        format.html { render :new }
        format.json { render json: @factoriall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /factorialls/1
  # PATCH/PUT /factorialls/1.json
  def update
    respond_to do |format|
      if @factoriall.update(factoriall_params)
        format.html { redirect_to @factoriall, notice: 'Factoriall was successfully updated.' }
        format.json { render :show, status: :ok, location: @factoriall }
      else
        format.html { render :edit }
        format.json { render json: @factoriall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factorialls/1
  # DELETE /factorialls/1.json
  def destroy
    @factoriall.destroy
    respond_to do |format|
      format.html { redirect_to factorialls_url, notice: 'Factoriall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factoriall
      @factoriall = Factoriall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factoriall_params
      params.require(:factoriall).permit(:n, :result)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/factorialls_helper.rb
module FactoriallsHelper
end

app/views/factorialls/_form.html.erb
<%= form_for(@factoriall) do |f| %>
  <% if @factoriall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@factoriall.errors.count, "error") %> prohibited this factoriall from being saved:</h2>

      <ul>
      <% @factoriall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :n %><br>
    <%= f.text_field :n %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_field :result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factorialls/edit.html.erb
<h1>Editing Factoriall</h1>

<%= render 'form' %>

<%= link_to 'Show', @factoriall %> |
<%= link_to 'Back', factorialls_path %>

app/views/factorialls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Factorialls</h1>

<table width="100%">
  <thead>
    <tr>
      <th style="text-align: center;">N</th>
      <th style="text-align: left;">Log2 (26^n)!</th>
    </tr>
  </thead>

  <tbody>
    <% @factorialls.each do |factoriall| %>
      <tr>
        <td style="text-align: center;"><%= factoriall.n %></td>
        <td style="text-align: left;"><%= factoriall.result %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Factoriall', new_factoriall_path %>

app/views/factorialls/new.html.erb
<h1>New Factoriall</h1>

<%= render 'form' %>

<%= link_to 'Back', factorialls_path %>

app/views/factorialls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>N:</strong>
  <%= @factoriall.n %>
</p>

<p>
  <strong>Result:</strong>
  <%= @factoriall.result %>
</p>

<%= link_to 'Edit', edit_factoriall_path(@factoriall) %> |
<%= link_to 'Back', factorialls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>